sudo: required
services:
  - docker

before_install:
  - docker build -t rajender/react-docker -f Dockerfile.dev .

script:
  - docker run rajender/react-docker npm test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-777282344989"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

